### ISSUE TITLE
Autoprefixer with postcss out of the box

### ISSUE THREAD

**Issue by yakovkhalinsky** [zhaoshengjun/webpack-config#1]
Would be awesome if postcss + autoprefixer was configured for the default setup 👍

**Comment by zhaoshengjun** [comment]
sure, I can add this.

**Comment by zhaoshengjun** [comment]
Hi @yakovkhalinsky, I just pushed a new version to add support postcss and autoprefixer. 

Let me know if you have any problem with the new version.

Thanks!

Happy coding!:smile:

**Comment by zhaoshengjun** [comment]
close issue.

**Comment by yakovkhalinsky** [comment]
@zhaoshengjun thanks for the quick update will enjoy using this 👍
