### ISSUE TITLE
Request: update the node modules

### ISSUE THREAD

**Issue by rbatllet** [zhaoshengjun/webpack-config#3]
Could you update the node modules using for example the npm-check-updates
(https://github.com/tjunnone/npm-check-updates) because they are a bit outdated.

![screen shot 2016-10-17 at 17 26 02](https://cloud.githubusercontent.com/assets/3993987/19443968/dd02e5fc-948e-11e6-822e-f21eaf150987.png)

**Comment by zhaoshengjun** [comment]
publish version 0.2.1 to close this.
