### ISSUE TITLE
 webpack-config: command not found

### ISSUE THREAD

**Issue by weswithley** [zhaoshengjun/webpack-config#4]
Hi,

I'm trying to use this plugin.
and the "npm i create-webpack-config" step is fine. ( i didn't use the global install )
but "webpack-config init" just shown "webpack-config: command not found"
any idea about this?

Thanks a lot.

**Comment by TotalLag** [comment]
Hi,

The command will require that you install it globally.  If you didn't install it globally, you'll have to create a "script" section inside package.json for npm to run "webpack-config init" since you installed it locally.

**Comment by weswithley** [comment]
ok,  I got it, Thx.
